// Java program to demonstrate
// finally block in java When
// exception does not rise

import java.io.*;

class GFG {
	public static void main(String[] args)
	{
		try {
			System.out.println("inside try block");
			
			
			System.out.println(34 / 2);
		}
		
		
		catch (ArithmeticException e) {
			
			System.out.println("Arithmetic Exception");
			
		}
		
		finally {
			
			System.out.println(
				"finally : i execute always.");
			
		}
	}
}
